-- agent-crm v0: SUPERSEDED.
--
-- This migration originally tried to use ALTER DATABASE SET app.* GUCs to
-- configure the Inngest publish triggers. Hosted Supabase blocks that for the
-- postgres user, so the GUC approach is dead.
--
-- Migration 0018 replaces it: notify_inngest_signal/gate read from
-- Supabase Vault instead, and scripts/setup_inngest_publishing.ts handles
-- the one-time vault secret creation.
--
-- Kept as a placeholder for migration ordering; this file is intentionally
-- a no-op.
select 1;
